server:
  port: 9091

spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: resourceserver
          client-secret: resourceserversecret
          introspection-uri: http://localhost:8080/oauth/check_token

logging:
  level:
    org.springframework: debug
